spring:
  application:
    name: message-service
platform:
  message:
    bounded-context: message-channel
    public-base-path: /api/messages
    scheduler-enabled: true
    retry-enabled: true
    max-retry-attempts: 3
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health,info
